### ISSUE TITLE
Homebrew distribution: support for High Sierra 

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#101]
@CharlieC3 What's your take on configuring the homebrew formula to support macOS `N` + `N-1` ?

**Comment by CharlieC3** [comment]
Can you provide more context? Why wouldn't it be supported by default?

**Comment by vysegrad** [comment]
@CharlieC3 i have tried to install Clarinet through Homebrew on High Sierra, it fails with an error message that it is not supported.

**Comment by CharlieC3** [comment]
@lgalabru the homebrew formula already supports `N`, `N-1`, and `N-2` (Big Sur, Catalina, Mojave). High Sierra is technically `N-3`. According to the [Homebrew release notes](https://brew.sh/2020/12/01/homebrew-2.6.0/), High Sierra hasn't been supported since Dec 2020. I don't think there's anything _we_ can do to add back support for High Sierra in homebrew.

@vysegrad Are you able to install Clarinet via macos binary under the releases page? https://github.com/hirosystems/clarinet/releases/tag/v0.15.0

**Comment by lgalabru** [comment]
Oh I thought High Sierra was N-1, my bad, I should have checked.
Supporting N-3 sounds like a stretch - there are other distros that should be prioritized.
@vysegrad you can look into the release page, as suggested by Charlie, or install from source via cargo - pretty straightforward, instructions are here https://github.com/hirosystems/clarinet#install-from-source-using-cargo.

**Comment by vysegrad** [comment]
thanks @CharlieC3 and @Igalabru the install-from-binary-release route worked.
