### ISSUE TITLE
Release workflow is broken

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#125]
The action of opening a pull request `release: 0.x.0` from develop to master do not trigger the release workflow like it use to do. Wonder what breaks and what I'm missing.
Summoning @CharlieC3 :)

**Comment by CharlieC3** [comment]
The issue seems to be that PRs are being squashed into the `main` branch, and that the squash commit isn't a valid conventional commit message. When that happens, the semantic release plugin cannot see the full history of the PR's commits, so it doesn't create a new tag:
https://github.com/hirosystems/clarinet/runs/3695937752?check_suite_focus=true#step:3:48

Instead of squashing, you can instead just merge normally. Or if you'd like to continue squashing, ensure the PR's squash commit follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) to have it rev properly (`release: <text>` is not a valid conventional commit type).

This is causing subsequent workflows to fail, so correcting this behavior might fix it for the lot :)

**Comment by lgalabru** [comment]
Ha interesting, thank you @CharlieC3!
