### ISSUE TITLE
No output when I run `clarinet console` in contract directory

### ISSUE THREAD

**Issue by Oyeins-GUI** [hirosystems/clarinet#1296]
**Describe the bug**
I get no output when I run the `clarinet console` command in my contract directory

**To Reproduce**
There are no steps to reproduce the issue, it just happened after I cloned a repo, made some changes to the clarity code and wanted to test it with the console, then this happened

**Expected behavior**
It's suppose to open up the repl to simulate the true blockchain state locally

**Screenshots**
![clarinet no output](https://github.com/hirosystems/clarinet/assets/104744427/e2499e2f-53e1-4b54-b975-c7e95aacac7b)

**Environment:**
 - OS (windows 10 pro 64-bit)
 - Clarinet version 2.0.0

**Additional context**
```
[project]
name = 'test'
description = ''
authors = []
telemetry = true
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP2KAF9RF86PVX3NEE27DFV1CQX0T4WGR41X3S45C.conversion'
[contracts.chess-on-chain]
path = 'contracts/test.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
```

**Comment by hugocaillard** [comment]
Hello @Oyeins-GUI,
Thanks for reporting this issue. I couldn't find any obvious reason for it, it looks like we'll need more details for the "steps to reproduce".

>  it just happened after I cloned a repo, made some changes to the clarity code

What repo? What changes?
Did you have the bug before the changes you made?

I saw you closed this issue, but even if you fixed the issue, I'd like to understand it so that we can display an error message when it happens
