### ISSUE TITLE
create `clarinet platform` commands

### ISSUE THREAD

**Issue by ryanwaits** [hirosystems/clarinet#1498]
I'm not sure if this has been discussed in other mediums or channels, but I've always loved the idea of a tighter integration between the `clarinet` CLI and the Hiro Platform. This came to mind after going through the guide on [how to connect your local editor to the platform](https://docs.hiro.so/stacks/platform/guides/connect-desktop-to-cloud). Similar to the Heroku CLI, we could simplify this approach with the following:
 - `clarinet platform login` 
 - `clarinet platform clone <project-id>`
 - `clarinet platform deploy <project-id>`

---

## Add `clarinet platform login`
This command would handle logging into the Hiro Platform, storing user credentials, and setting up the environment for subsequent CLI commands.

## Add `clarinet platform clone <project-id>` command
This command clones a hosted project from the Hiro Platform into the local environment, analogous to `git clone`.

- Retrieves the project from the Hiro Platform using the provided URL.
- Generates/uses an existing SSH key and registers it with the Hiro Platform.
- Configures necessary settings for future interactions.
- Clones the project into the local directory.

> _Other familiar `git` commands like `fetch`, `pull`, can also be implemented_

## Add `clarinet platform deploy <project-id>` command
Initiate the deployment of the project on the Hiro Platform. Available flags could include `--network`

**Comment by hugocaillard** [comment]
Yes! It's been discussed, but maybe not on public channels.

Some thoughts:

- we could potentially avoid the `platform` keyword, just do `clarinet login`
- not sure `clone` is something we want, imo it'd be great if the Platform projects were managed with git/github. More like what Vercel does
- `deploy` requires some thoughts, because it overlaps with `clarinet deployments`
  - starting a devnet in the cloud would be amazing (something like `clarinet devnet start --online`)
  
Maybe we should move the discussion to Notion or [Github Discussion](https://github.com/hirosystems/clarinet/discussions) while we are in the design phase. 
 
Note: For an other project (more details soon), we'll soon have a need for `clarinet login` and api key management, so that's definitely something we want to put in motion soon

**Comment by ryanwaits** [comment]
good idea, moved it over to discussions https://github.com/hirosystems/clarinet/discussions/1501
