### ISSUE TITLE
`host.docker.internal` is not avaliable on Linux

### ISSUE THREAD

**Issue by LNow** [hirosystems/clarinet#94]
I've tried to use `clarinet integrate` command, and unfortunately it doesn't work on Linux machines.
The reason for that is on Linux `host.docker.internal` is not available. Linux equivalent of this host name is 172.17.0.1 (by default).

**Comment by dantrevino** [comment]
Isn't this something that can be set conditionally based on os?

**Comment by LNow** [comment]
On linux to have access to `host.docker.internal` inside container we have to add it explicitly to container. For example:
```sh
$ docker run --rm -it --add-host=host.docker.internal:host-gateway node:lts-alpine3.14
```

**Comment by lgalabru** [comment]
To be addressed with https://github.com/hirosystems/clarinet/pull/100

**Comment by zone117x** [comment]
The stacks-blockchain-api ran into this with github CI ubuntu runners. Was able to use this (quite old) docker entry script to create `host.docker.internal` when running in linux:
https://github.com/bufferings/docker-access-host/blob/master/docker-entrypoint.sh

I also had to disable the gh ubuntu firewall for this to work, but since then, it's been working well.

**Comment by lgalabru** [comment]
Confirmed with @LNow - #100 is fixing the issue.
