### ISSUE TITLE
Local `integrate` devnet halts after ~90 minutes

### ISSUE THREAD

**Issue by hstove** [hirosystems/clarinet#974]
When running `clarinet integrate` (latest clarinet, macos arm, default devnet.toml images), the devnet consistently halts after about 90 minutes. When I try and debug the cause, I see that the stacks-node image is dead, but all other images are still running fine. Bitcoin blocks can be mined (manually) but without stacks blocks. I've seen this behavior across different `stacks_node_image_url` versions too.

I've tried running `docker logs -f stacks-node.<network>.devnet`, but I don't see anything unusual in the log output. It just "stops". No unusual logs in `devnet.log` either. If you can think of something else to debug this, I'm happy to do so.

**Comment by hstove** [comment]
> Does it happen at a certain block height?

No, it doesn't appear so. I have also tried modifying block time to see if it's height-related, but found that it always happened after 90 minutes +- ~10 minutes

**Comment by hstove** [comment]
A different side-effect is that, once this happens, quitting the process with ctrl-c hangs/fails. I assume because the `stacks-node` container is dead, and the Clarinet orchestrator is trying to shut it down and failing. You have to hit ctrl-c again which leaves a bunch of hung running containers, which you have to stop manually before running `clarinet integrate` again. You also need to run `docker network prune` to clean up the network.

**Comment by hugocaillard** [comment]
I set the priority to high and raised the size to M. Could be lowered after investigation

**Comment by MicaiahReid** [comment]
I'm thinking that both this issue and #1099 are due to the docker container running out of memory. This will be at a different number of blocks depending on your docker settings. It was consistently at around 120 blocks for me when I had 8 GB allocated for the all containers, and it's up to around 180 blocks when I've increased the allocation to 13 GB. How many blocks you make it to will also depend on what other containers you have running simultaneously.

The stacks node _by far_ uses the most memory. Currently it is using 8.67 GB while the next highest, the stacks-api, is using just 351 MB.

After long enough, this can cause the stacks node to crash while the other containers continue to run, which explains why specifically the stacks node in #1099 stops responding.

I will investigate what exactly is taking up so much RAM on the stacks node side. Maybe it's a memory leak in the image we're using, or maybe it's something with the way we're configuring it.

**Comment by hstove** [comment]
Interesting - thanks, makes sense. I have an M1 with 8GB so that explains why I ran into a faster crash. It sounds like there's no easy fix here, but a small improvement would be to detect a crash and gracefully end the `clarinet integrate` environment, with an error message about what happened. Otherwise, I'm sure users have trouble figuring out that they need to manually stop all the other containers before restarting.

It is odd that the stacks node uses so much memory. Myself and many others are running Stacks nodes in production with Docker and 4GB machines.

**Comment by MicaiahReid** [comment]
I've done some further digging, and the following field can be enabled in your `Devnet.toml`:
```toml
bind_containers_volumes = true
```
This will have the docker container volumes bind to your local filesystem, so that chainstate is written on disk rather than in memory.

However, I've had problems with this on mac - docker/clarinet do not show any errors, but everything is still written to memory rather than disk. On linux, this feature works fine.

I'm going to close this issue for now, but I'd love to hear from any users that are still having this problem after enabling the `bind_containers_volumes` flag - what OS are you running, and what version of docker desktop?
